const woodPresets = {
  oak: {
    name: '橡木 (Oak)',
    description: '经典浅橡木，纹理清晰自然',
    baseColor: '#C8A27B',
    grainColor: '#8B6914',
    density: 28,
    depth: 52,
    angle: 0,
    thickness: 6,
    noise: 45,
    knots: 5,
    irregularity: 55,
    ringSpacing: 28
  },
  walnut: {
    name: '胡桃木 (Walnut)',
    description: '深褐色名贵胡桃木，纹理优雅',
    baseColor: '#5C4033',
    grainColor: '#2D1810',
    density: 35,
    depth: 58,
    angle: 0,
    thickness: 5,
    noise: 40,
    knots: 3,
    irregularity: 60,
    ringSpacing: 32
  },
  cherry: {
    name: '樱桃木 (Cherry)',
    description: '暖红色樱桃木，色泽温润',
    baseColor: '#A83C32',
    grainColor: '#6B2020',
    density: 32,
    depth: 48,
    angle: 0,
    thickness: 5,
    noise: 35,
    knots: 2,
    irregularity: 45,
    ringSpacing: 30
  },
  maple: {
    name: '枫木 (Maple)',
    description: '浅色硬枫木，纹理细腻',
    baseColor: '#F5E6D3',
    grainColor: '#C9A86C',
    density: 42,
    depth: 42,
    angle: 0,
    thickness: 4,
    noise: 38,
    knots: 1,
    irregularity: 40,
    ringSpacing: 25
  },
  mahogany: {
    name: '桃花心木 (Mahogany)',
    description: '红棕色调，纹理平直优美',
    baseColor: '#8B3A3A',
    grainColor: '#4A1C1C',
    density: 25,
    depth: 55,
    angle: 0,
    thickness: 7,
    noise: 32,
    knots: 2,
    irregularity: 35,
    ringSpacing: 35
  },
  teak: {
    name: '柚木 (Teak)',
    description: '金黄色调，纹理粗犷自然',
    baseColor: '#B8860B',
    grainColor: '#6B4423',
    density: 22,
    depth: 60,
    angle: 0,
    thickness: 8,
    noise: 50,
    knots: 6,
    irregularity: 70,
    ringSpacing: 38
  },
  ebony: {
    name: '乌木 (Ebony)',
    description: '深黑褐色，质地坚硬细密',
    baseColor: '#2C1810',
    grainColor: '#0D0706',
    density: 55,
    depth: 45,
    angle: 0,
    thickness: 3,
    noise: 25,
    knots: 0,
    irregularity: 30,
    ringSpacing: 18
  },
  ash: {
    name: '白蜡木 (Ash)',
    description: '米白色调，纹理粗犷明显',
    baseColor: '#E8DCC8',
    grainColor: '#A67C52',
    density: 30,
    depth: 50,
    angle: 0,
    thickness: 7,
    noise: 42,
    knots: 4,
    irregularity: 50,
    ringSpacing: 28
  },
  pine: {
    name: '松木 (Pine)',
    description: '浅黄色软木，节疤明显',
    baseColor: '#DAA520',
    grainColor: '#8B6914',
    density: 20,
    depth: 55,
    angle: 0,
    thickness: 8,
    noise: 55,
    knots: 8,
    irregularity: 65,
    ringSpacing: 40
  },
  bamboo: {
    name: '竹纹 (Bamboo)',
    description: '仿竹纹理，清新自然',
    baseColor: '#D2B48C',
    grainColor: '#8B7355',
    density: 60,
    depth: 40,
    angle: 0,
    thickness: 2,
    noise: 20,
    knots: 0,
    irregularity: 25,
    ringSpacing: 15
  },
  rosewood: {
    name: '红木 (Rosewood)',
    description: '深紫红色，纹理交错',
    baseColor: '#6B2D5A',
    grainColor: '#3D0C2E',
    density: 45,
    depth: 65,
    angle: 15,
    thickness: 4,
    noise: 48,
    knots: 3,
    irregularity: 75,
    ringSpacing: 22
  },
  zebrawood: {
    name: '斑马木 (Zebrawood)',
    description: '深浅条纹对比鲜明',
    baseColor: '#C4A66B',
    grainColor: '#3D2817',
    density: 38,
    depth: 70,
    angle: 10,
    thickness: 6,
    noise: 30,
    knots: 2,
    irregularity: 55,
    ringSpacing: 25
  }
};

export default woodPresets;
